### ISSUE TITLE
SSL Zookeeper support 

### ISSUE THREAD

**Issue by arvdias** [newrelic/nri-kafka#100]
## Is your feature request related to a problem? Please describe.

We are seeing errors when connecting to Zookeeper with SSL enabled. This may be related to missing SSL support in the library being used. See https://github.com/samuel/go-zookeeper/issues/161

## Feature Description

Add support for connecting to Zookeeper with SSL

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Must Have]

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
