### ISSUE TITLE
Ruby Consumers, NodeJS Consumers

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kafka#110]
## Feature Description

Currently we support Java based only consumer and producers. 
We should support a wider range if possible. 

## Describe Alternatives
There is not a real alternative. The only one would be to use nri-prometheus together with an exporter. 
This solution however would lead to a completely different user experience since every metric name would change and it would generate DMs and not samples.

## Priority
Needed feature

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
