### ISSUE TITLE
include jmx from sdk v3 

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-kafka#113]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Problem: when SDK receives any warning from NRJMX integration, it stops to process remaining data. It has race condition inside, so sometimes it will process data first and exits, in some cases it will print warning first and exits.

The version of the integrations-sdk needs to be bumped when [this issue](https://github.com/newrelic/infra-integrations-sdk/issues/261) is resolved

**Comment by roobre** [comment]
Closing as this fix was added in #111
