### ISSUE TITLE
Not able to build the image using Dockerfile for https://github.com/newrelic/nri-kafka

### ISSUE THREAD

**Issue by mbarua-opentext** [newrelic/nri-kafka#136]
## Description
When trying to build the docker image using the command: **docker build -t nri-kafka .** getting below error

![image](https://user-images.githubusercontent.com/60379725/123813643-b4bf3280-d912-11eb-9979-1ffda00ab215.png)

## Expected Behavior
If I need to pass any other variables as arg then please let me know. 

## Steps to Reproduce
1. Download the repo
2. run the command: docker build -t nri-kafka .

**Comment by roobre** [comment]
Hi!

I'm sorry for the confusion, the `Dockerfile` present in this repo is only for development purposes and it is not intended to be used by end users.

We currently do not provide individual docker images for each integration, but we do have one which contains most of them: https://hub.docker.com/r/newrelic/infrastructure-bundle.

You can see details on how to build and use this image in https://github.com/newrelic/infrastructure-bundle.

However, if you want to build the integration locally, with the `go` command installed, running

```
go build -o nri-kafka ./src/
```

should suffice.
