### ISSUE TITLE
SASL_SSL and PLAIN support in non-Kerberos environments

### ISSUE THREAD

**Issue by vpoyraz** [newrelic/nri-kafka#148]
## Is your feature request related to a problem? Please describe.
Currently there is support for PLAIN SASL mechanism but this does not extend to SASL_SSL based security profiles. There are presumably a lot of clients that would be in a non-Kerberos environment and presently are unable to utilise this awesome integration with Kafka/Confluent Platform that uses SASL_SSL + PLAIN mechanism.

We use JAAS configuration to connect to multiple Confluent Platform environments and standalone service accounts (with API keys) with the Plain login module works really well.

Example JAAS configuration looks like the below with this SASL security profile:

```bootstrap.servers=<broker-list>
broker.address.ttl=30000
api.version.request=true
api.version.fallback.ms=0
broker.version.fallback=0.10.0.0
security.protocol=SASL_SSL
ssl.ca.location=/usr/local/etc/openssl/cert.pem
sasl.mechanisms=PLAIN
sasl.username=<api-key>
sasl.password=<api-secret>
session.timeout.ms=45000
```
ref: https://docs.confluent.io/cloud/current/client-apps/config-client.html

## Feature Description
Support for SASL PLAIN mechanism to work with SASL_SSL for encryption of API key based authentication, not just Kerberos with this security procol.

There is further information for the Confluent Platform that goes into detail around the usage of API keys with SASL_SSL auth using the PLAIN mechanism (https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_plain.html)

## Describe Alternatives
None applicable

## Priority
Blocker

**Comment by davidgit** [comment]
Hi ,  

The next best step is to visit [New Relic Feature Requests Portal](https://newrelic.ideas.aha.io/), where you can engage with the Product Manager team and submit your request.

Thanks!

**Comment by vpoyraz** [comment]
Hi @davidgit,

I was under the impression we were able to raise feature requests here, your README.md seems to be incorrect/outdated if that is no longer the case:

## Support

Should you need assistance with New Relic products, you are in good hands with several support diagnostic tools and support channels.

> New Relic offers NRDiag, [a client-side diagnostic utility](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) that automatically detects common problems with New Relic agents. If NRDiag detects a problem, it suggests troubleshooting steps. NRDiag can also automatically attach troubleshooting data to a New Relic Support ticket.

**If the issue has been confirmed as a bug or is a Feature request, please file a Github issue.** << HERE

**Support Channels**

* [New Relic Documentation](https://docs.newrelic.com): Comprehensive guidance for using our platform
* [New Relic Community](https://discuss.newrelic.com): The best place to engage in troubleshooting questions
* [New Relic Developer](https://developer.newrelic.com/): Resources for building a custom observability applications
* [New Relic University](https://learn.newrelic.com/): A range of online training for New Relic users of every level
* [New Relic Technical Support](https://support.newrelic.com/) 24/7/365 ticketed support. Read more about our [Technical Support Offerings](https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/support-plan).

Cheers
