### ISSUE TITLE
Improve Consumer/Producer JMX metrics collection

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-kafka#159]
Right now, when setting Consumer/Producer Jmx collection the user needs to set:

- Name: It's the consumer/producer client.id and it's difficult to know unless specifically set in the code.
- JMX_host.
- JMX_port.

We would like to try to auto-detect the name of the consumer/producer so the user would only need to set the host and port.

**Comment by davidgit** [comment]
Let's first perform a spike to agree on a solution.
