### ISSUE TITLE
Review: Java agent-> Instrument Kafka message queues

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kafka#164]
## Is your feature request related to a problem? Please describe.
It is always complex to setup monitoring for consumer and producers. Chris Conde pointed out a feature from the APM newrelic agent that would make sense to investigate.

We should understand and document:
 - if the two solutions overlap
 - if the two solutions are compatible
 - if we can deprecate some of the metrics we are currently collecting in favour of these ones

[Related docs](https://docs.newrelic.com/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues/#collect-kafka-events)
[More context](https://newrelic.slack.com/archives/CP2EWSX7C/p1646864520567989)

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have]

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
