### ISSUE TITLE
Float64 Issue realted to Topic Size

### ISSUE THREAD

**Issue by wildcardlinux** [newrelic/nri-kafka#183]
## Description
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-KSTREAM-OUTERTHIS-0000000105-store-repartition: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-KSTREAM-OUTERTHIS-0000000105-store-repartition,partition=3,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic connect-cluster-offsets: unable to cast bean 'kafka.log:type=Log,name=Size,topic=connect-cluster-offsets,partition=4,attr=Value' value '150150' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-expected-group-consumption-rekey: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-expected-group-consumption-rekey,partition=9,attr=Value' value '9630796' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-AlertHistoryStore-changelog: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-AlertHistoryStore-changelog,partition=6,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-Group-ONE_MINUTE-repartition: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-Group-ONE_MINUTE-repartition,partition=5,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-Group-THREE_HOURS-repartition: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-Group-THREE_HOURS-repartition,partition=3,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-MonitoringStream-THREE_HOURS-changelog: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-MonitoringStream-THREE_HOURS-changelog,partition=5,attr=Value' value '3843' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-AlertHistoryStore-repartition: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-AlertHistoryStore-repartition,partition=11,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic prior-auth-inbound-test: unable to cast bean 'kafka.log:type=Log,name=Size,topic=prior-auth-inbound-test,partition=3,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-license: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-license,partition=0,attr=Value' value '2804' as float64" role=kafka
time="2022-06-29T09:43:07Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent_balancer_broker_samples: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent_balancer_broker_samples,partition=6,attr=Value' value '27450' as float64" role=kafka
time="2022-06-29T09:43:08Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-MonitoringTriggerStore-changelog: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-MonitoringTriggerStore-changelog,partition=1,attr=Value' value '0' as float64" role=kafka
time="2022-06-29T09:43:08Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=dev integration_name=nri-kafka line="[ERR] Unable to calculate size for Topic _confluent-controlcenter-6-1-0-1-aggregatedTopicPartitionTableWindows-ONE_MINUTE-changelog: unable to cast bean 'kafka.log:type=Log,name=Size,topic=_confluent-controlcenter-6-1-0-1-aggregatedTopicPartitionTableWindows-ONE_MINUTE-changelog,partition=1,attr=Value' value '0' as float64" role=kafka
debug2: channel 0: window 999214 sent adjust 49362

## Additional context
[Link to Community Post](https://discuss.newrelic.com/t/nri-kafka-integration-errors-with-collect-topic-size-and-collect-topic-offset-set-to-true/187879)

[nri-kafka.txt](https://github.com/newrelic/nri-kafka/files/9049067/nri-kafka.txt)
[newrelic-infra.txt](https://github.com/newrelic/nri-kafka/files/9049068/newrelic-infra.txt)
[kafka-config.txt](https://github.com/newrelic/nri-kafka/files/9049070/kafka-config.txt)

**Comment by davidgit** [comment]
Hi @wildcardlinux , 

The next best step is to open a Support ticket.

Thanks!
