### ISSUE TITLE
Collect topic size and offset failing due to wrong format conversion

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-kafka#188]
When setting the flag collect_topic_size and/or collect_topic_size the value retrieved from the MBean is a string and is forcefully casted to float64 so it fails, we need to parse it from string to float64.

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/3638421/182386661-fe305762-525a-45b7-9598-ea705a92c294.png">

Add also this labels to bootstrapDiscoverConfig in integration_test :
```
"--collect_topic_size",
"--collect_topic_offset",
```

**Comment by tejas238** [comment]
Hi, just wanted to acknowledge the issue and the problem statement looks correct. In how much time can I expect a resolution?

**Comment by alvarocabanas** [comment]
This [PR](https://github.com/newrelic/nri-kafka/pull/193) solves the issue and it's included in the latest release [v3.2.0](https://github.com/newrelic/nri-kafka/releases/tag/v3.2.0)
