### ISSUE TITLE
Attach pre-built binaries to each github release.

### ISSUE THREAD

**Issue by jeckhart** [newrelic/nri-kafka#46]
##### Description of the problem
The newrelic/nri-zookeeper project attaches built binaries to the release for each release. This simplifies installation as the binaries are already built.

Could we have the same thing done here, where the binaries are attached to the release?

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
Tarballs are available on the NewRelic downloads pages https://docs.newrelic.com/docs/integrations/host-integrations/installation/install-host-integrations-built-new-relic#tarball
