### ISSUE TITLE
getting error  "host could not be found for broker "

### ISSUE THREAD

**Issue by mahesh123bangalore** [newrelic/nri-kafka#52]
##### Description of the problem

Hi,

Iam getting an error when newrelic is trying to connect to brokers for JMX information.

error says  " **[ERR] Unable to get broker JMX information for broker id : host could not be found for broker**"
i debugged the nri-kafka code and found that it was thrown from  " **nri-kafka/src/zookeeper/connection.GetBrokerConnectionInfo()** "

Please find the code snippet from GetBrokerConnectionInfo() below.

	**// We only want the URL if it's SSL or PLAINTEXT
	scheme, brokerURLString, err := func() (scheme, brokerURLString string, err error) {
		for _, urlString := range brokerDecoded.Endpoints {
			if strings.HasPrefix(urlString, "SSL") {
				brokerURLString = urlString
				scheme = "https"
				return
			} else if strings.HasPrefix(urlString, "PLAINTEXT") {
				brokerURLString = urlString
				scheme = "http"
				return
			}
		}

		return "", "", errors.New("host could not be found for broker")**

above code is expecting either SSL or PLAINTEXT as a prefix for the endpoints.But the json returned by zookeeper will not contian SSL or PLAINTEXT as prefix. prefixes are defined in listener_security_protocol_map and has been used in endpoints.

Please find the json returned by the zookeeper in my local setup.

**{"listener_security_protocol_map":{"LISTENER_DOCKER_INTERNAL":"PLAINTEXT","LISTENER_DOCKER_EXTERNAL":"PLAINTEXT"},"endpoints":["LISTENER_DOCKER_INTERNAL://kafka:19092","LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092"],"jmx_port":9999,"host":"kafka","timestamp":"1557466544710","port":19092,"version":4}**

**Comment by ccheek21** [comment]
Should be fixed by #60
