### ISSUE TITLE
nri-kafka does not support SASL_PLAINTEXT security protocol

### ISSUE THREAD

**Issue by mafitconsulting** [newrelic/nri-kafka#58]
##### Description of the problem

It appears as though the nri-kafka integration does not support sasl-plaintext. See F/R below
https://discuss.newrelic.com/t/feature-idea-nri-kafka-sasl-plaintext-support/63261

Error when trying to get broker information
` level=error msg="executing data source" data prefix=config/kafka error="exit status 1" plugin name=kafka-consumer-offsets stderr="2019/07/22 10:32:38 Connected to 100.98.200.70:2181\n2019/07/22 10:32:38 Authenticated: id=102416806283784402, timeout=4000\n2019/07/22 10:32:38 Re-submitting `0` credentials after reconnect\n[WARN] Unable to get connection information for broker with ID '1'. Will not collect offset data for consumer groups on this broker.\n[WARN] Unable to get connection information for broker with ID '2'. Will not collect offset data for consumer groups on this broker.\n[WARN] Unable to get connection information for broker with ID '3'. Will not collect offset data for consumer groups on this broker.\n[ERR] Failed collecting consumer offset data: kafka: invalid configuration (You must provide at least one broker address)\n"
`

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by ccheek21** [comment]
@mafitconsulting Sorry for the slow response on this. I've got this on my list to look into in the next week or so

**Comment by ccheek21** [comment]
Update on this: currently blocked by a couple of issues upstream. 

https://github.com/Shopify/sarama/issues/1526
https://github.com/Shopify/sarama/issues/1519

**Comment by RagingPuppies** [comment]
why is the use of "HasPrefix" ? as i understand it will only look for the start of a string, using SASL_SSL or SASL_PLAINTEXT will make it fail...

line 220  of src/zookeeper/connection.go
if strings.HasPrefix(urlString, "SSL") || (hasProtocol && strings.HasPrefix(urlStringProtocol, "SSL")) {

**Comment by martelskiy** [comment]
Any updates on this?

**Comment by camdencheek** [comment]
We've refactored the codebase so it doesn't have the confusing `HasPrefix` stuff. However, it's still blocked on those sarama issues.

**Comment by dylanmei** [comment]
It's unclear what those Kerberos issues have to do with supporting SASL mechanisms PLAIN and SCRAM. Sarama has examples: https://github.com/Shopify/sarama/tree/master/examples/sasl_scram_client

**Comment by camdencheek** [comment]
@dylanmei -- you're right. For some reason I got it in my head that the feature being requested here was specifically for the GSSAPI method. I'll add it to my backlog, but in the mean time, would be happy to review any PRs to add non-GSSAPI SASL auth

**Comment by camdencheek** [comment]
Fixed in #82
