### ISSUE TITLE
Select kafka connection protocol in the config.

### ISSUE THREAD

**Issue by antondalgren** [newrelic/nri-kafka#64]
##### Description of the problem
It would be nice if you could specify what kafka protocol you would want the plugin to connect to.

Our setup is using multiple listeners defined in the `server.properties` file on a kafka cluster.
`advertised.listeners=SSL://HOSTNAME:PORT,SASL_SSL://HOSTNAME:PORT,PLAINTEXT://HOSTNAME:PORT`
The current implementation will only create a connection string to the first occurring listener in the `advertised.listeners` property.  If you were instead making an array of connection strings using different protocols i.e `SSL` and `PLAINTEXT` it would open up for the possibility to use the second connection string if the first one fails. With this suggested implementation, a user would be allowed to explicitly select a specific protocol type from the config file.

https://github.com/newrelic/nri-kafka/blob/775ddb5e5ef112ee6e10fdc7770d51fb9000be19/src/zookeeper/connection.go#L40#L76
&
https://github.com/newrelic/nri-kafka/blob/775ddb5e5ef112ee6e10fdc7770d51fb9000be19/src/zookeeper/connection.go#L163#L199

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by camdencheek** [comment]
Thanks for the report. Forgot to notify here, but this made it into the last batch of fixes. This can now be done with the `preferred_listener` argument
